# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetWawEventCountryList(BaseModel):
    get_waw_event_country_list: Optional[
        List[Optional["GetWawEventCountryListGetWawEventCountryList"]]
    ] = Field(alias="getWawEventCountryList")


class GetWawEventCountryListGetWawEventCountryList(BaseModel):
    letter: Optional[str]
    countries: Optional[
        List[Optional["GetWawEventCountryListGetWawEventCountryListCountries"]]
    ]


class GetWawEventCountryListGetWawEventCountryListCountries(BaseModel):
    name: Optional[str]
    code: Optional[str]
    slug: Optional[str]


GetWawEventCountryList.model_rebuild()
GetWawEventCountryListGetWawEventCountryList.model_rebuild()
