# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetCISCompetitorResDisp(BaseModel):
    get_cis_competitor_res_disp: Optional[
        "GetCISCompetitorResDispGetCisCompetitorResDisp"
    ] = Field(alias="getCISCompetitorResDisp")


class GetCISCompetitorResDispGetCisCompetitorResDisp(BaseModel):
    parameters: Optional["GetCISCompetitorResDispGetCisCompetitorResDispParameters"]
    active_years: Optional[List[Optional[str]]] = Field(alias="activeYears")
    results_by_event: Optional[
        List[Optional["GetCISCompetitorResDispGetCisCompetitorResDispResultsByEvent"]]
    ] = Field(alias="resultsByEvent")
    results_by_date: Optional[
        List[Optional["GetCISCompetitorResDispGetCisCompetitorResDispResultsByDate"]]
    ] = Field(alias="resultsByDate")


class GetCISCompetitorResDispGetCisCompetitorResDispParameters(BaseModel):
    results_by_year: Optional[int] = Field(alias="resultsByYear")
    results_by_year_order_by: Optional[str] = Field(alias="resultsByYearOrderBy")


class GetCISCompetitorResDispGetCisCompetitorResDispResultsByEvent(BaseModel):
    indoor: Optional[bool]
    discipline_code: Optional[str] = Field(alias="disciplineCode")
    discipline_name_url_slug: Optional[str] = Field(alias="disciplineNameUrlSlug")
    type_name_url_slug: Optional[str] = Field(alias="typeNameUrlSlug")
    discipline: Optional[str]
    with_wind: Optional[bool] = Field(alias="withWind")
    with_remark: Optional[bool] = Field(alias="withRemark")
    results: Optional[
        List[
            Optional[
                "GetCISCompetitorResDispGetCisCompetitorResDispResultsByEventResults"
            ]
        ]
    ]


class GetCISCompetitorResDispGetCisCompetitorResDispResultsByEventResults(BaseModel):
    date: Optional[str]
    competition: Optional[str]
    venue: Optional[str]
    indoor: Optional[bool]
    country: Optional[str]
    category: Optional[str]
    race: Optional[str]
    place: Optional[str]
    mark: Optional[str]
    wind: Optional[str]
    not_legal: Optional[bool] = Field(alias="notLegal")
    result_score: Optional[int] = Field(alias="resultScore")
    remark: Optional[str]


class GetCISCompetitorResDispGetCisCompetitorResDispResultsByDate(BaseModel):
    date: Optional[str]
    competition: Optional[str]
    venue: Optional[str]
    indoor: Optional[bool]
    country: Optional[str]
    category: Optional[str]
    race: Optional[str]
    place: Optional[str]
    mark: Optional[str]
    wind: Optional[str]
    not_legal: Optional[bool] = Field(alias="notLegal")
    result_score: Optional[int] = Field(alias="resultScore")
    remark: Optional[str]


GetCISCompetitorResDisp.model_rebuild()
GetCISCompetitorResDispGetCisCompetitorResDisp.model_rebuild()
GetCISCompetitorResDispGetCisCompetitorResDispResultsByEvent.model_rebuild()
