# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetAssetsTotal(BaseModel):
    get_assets_total: Optional["GetAssetsTotalGetAssetsTotal"] = Field(
        alias="getAssetsTotal"
    )


class GetAssetsTotalGetAssetsTotal(BaseModel):
    total: Optional[str]


GetAssetsTotal.model_rebuild()
