# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetVideosTotalNumber(BaseModel):
    get_videos_total_number: Optional[
        "GetVideosTotalNumberGetVideosTotalNumber"
    ] = Field(alias="getVideosTotalNumber")


class GetVideosTotalNumberGetVideosTotalNumber(BaseModel):
    total: Optional[str]


GetVideosTotalNumber.model_rebuild()
