# Generated by ariadne-codegen on 2024-07-13 19:17
# Source: graphql/queries.graphql

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class GetAssetsTotal(BaseModel):
    get_assets_total: Optional["GetAssetsTotalGetAssetsTotal"] = Field(
        alias="getAssetsTotal"
    )


class GetAssetsTotalGetAssetsTotal(BaseModel):
    total: Optional[str]


GetAssetsTotal.update_forward_refs()
GetAssetsTotalGetAssetsTotal.update_forward_refs()
