# Generated by ariadne-codegen on 2024-07-13 19:17
# Source: graphql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetRecordsDisciplineList(BaseModel):
    get_records_discipline_list: Optional[
        List[Optional["GetRecordsDisciplineListGetRecordsDisciplineList"]]
    ] = Field(alias="getRecordsDisciplineList")


class GetRecordsDisciplineListGetRecordsDisciplineList(BaseModel):
    gender: Optional[str]
    discipline_types: Optional[
        List[
            Optional["GetRecordsDisciplineListGetRecordsDisciplineListDisciplineTypes"]
        ]
    ] = Field(alias="disciplineTypes")


class GetRecordsDisciplineListGetRecordsDisciplineListDisciplineTypes(BaseModel):
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")
    disciplines: Optional[
        List[
            Optional[
                "GetRecordsDisciplineListGetRecordsDisciplineListDisciplineTypesDisciplines"
            ]
        ]
    ]


class GetRecordsDisciplineListGetRecordsDisciplineListDisciplineTypesDisciplines(
    BaseModel
):
    event_id: Optional[str] = Field(alias="eventId")
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")


GetRecordsDisciplineList.update_forward_refs()
GetRecordsDisciplineListGetRecordsDisciplineList.update_forward_refs()
GetRecordsDisciplineListGetRecordsDisciplineListDisciplineTypes.update_forward_refs()
GetRecordsDisciplineListGetRecordsDisciplineListDisciplineTypesDisciplines.update_forward_refs()
