# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetVocabulary(BaseModel):
    get_vocabulary: Optional["GetVocabularyGetVocabulary"] = Field(
        alias="getVocabulary"
    )


class GetVocabularyGetVocabulary(BaseModel):
    vocabulary: Optional[Any]


GetVocabulary.model_rebuild()
