# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetWawCompetitionEventsOrganizerDetails(BaseModel):
    get_waw_competition_events_organizer_details: Optional[
        List[
            Optional[
                "GetWawCompetitionEventsOrganizerDetailsGetWawCompetitionEventsOrganizerDetails"
            ]
        ]
    ] = Field(alias="getWawCompetitionEventsOrganizerDetails")


class GetWawCompetitionEventsOrganizerDetailsGetWawCompetitionEventsOrganizerDetails(
    BaseModel
):
    id: Optional[int]
    event_id_wa: Optional[int] = Field(alias="eventId_WA")
    name: Optional[str]
    start_date: Optional[Any] = Field(alias="startDate")
    venue: Optional[str]
    country_code: Optional[str] = Field(alias="countryCode")
    organizer_details: Optional[
        List[
            Optional[
                "GetWawCompetitionEventsOrganizerDetailsGetWawCompetitionEventsOrganizerDetailsOrganizerDetails"
            ]
        ]
    ] = Field(alias="organizerDetails")


class GetWawCompetitionEventsOrganizerDetailsGetWawCompetitionEventsOrganizerDetailsOrganizerDetails(
    BaseModel
):
    name: Optional[str]
    value: Optional[str]


GetWawCompetitionEventsOrganizerDetails.model_rebuild()
GetWawCompetitionEventsOrganizerDetailsGetWawCompetitionEventsOrganizerDetails.model_rebuild()
