# Generated by ariadne-codegen on 2024-07-13 19:17
# Source: graphql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetRecordsCategories(BaseModel):
    get_records_categories: Optional[
        List[Optional["GetRecordsCategoriesGetRecordsCategories"]]
    ] = Field(alias="getRecordsCategories")


class GetRecordsCategoriesGetRecordsCategories(BaseModel):
    id: Optional[int]
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")
    items: Optional[List[Optional["GetRecordsCategoriesGetRecordsCategoriesItems"]]]


class GetRecordsCategoriesGetRecordsCategoriesItems(BaseModel):
    id: Optional[int]
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")
    items: Optional[
        List[Optional["GetRecordsCategoriesGetRecordsCategoriesItemsItems"]]
    ]


class GetRecordsCategoriesGetRecordsCategoriesItemsItems(BaseModel):
    id: Optional[int]
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")
    items: Optional[
        List[Optional["GetRecordsCategoriesGetRecordsCategoriesItemsItemsItems"]]
    ]


class GetRecordsCategoriesGetRecordsCategoriesItemsItemsItems(BaseModel):
    id: Optional[int]
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")
    items: Optional[
        List[Optional["GetRecordsCategoriesGetRecordsCategoriesItemsItemsItemsItems"]]
    ]


class GetRecordsCategoriesGetRecordsCategoriesItemsItemsItemsItems(BaseModel):
    id: Optional[int]
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")
    items: Optional[
        List[
            Optional[
                "GetRecordsCategoriesGetRecordsCategoriesItemsItemsItemsItemsItems"
            ]
        ]
    ]


class GetRecordsCategoriesGetRecordsCategoriesItemsItemsItemsItemsItems(BaseModel):
    id: Optional[int]
    name: Optional[str]
    url_slug: Optional[str] = Field(alias="urlSlug")


GetRecordsCategories.update_forward_refs()
GetRecordsCategoriesGetRecordsCategories.update_forward_refs()
GetRecordsCategoriesGetRecordsCategoriesItems.update_forward_refs()
GetRecordsCategoriesGetRecordsCategoriesItemsItems.update_forward_refs()
GetRecordsCategoriesGetRecordsCategoriesItemsItemsItems.update_forward_refs()
GetRecordsCategoriesGetRecordsCategoriesItemsItemsItemsItems.update_forward_refs()
GetRecordsCategoriesGetRecordsCategoriesItemsItemsItemsItemsItems.update_forward_refs()
