# Generated by ariadne-codegen
# Source: graphql/queries.graphql

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel


class VerifyCaptchaToken(BaseModel):
    verify_captcha_token: Optional["VerifyCaptchaTokenVerifyCaptchaToken"] = Field(
        alias="verifyCaptchaToken"
    )


class VerifyCaptchaTokenVerifyCaptchaToken(BaseModel):
    is_success: Optional[bool] = Field(alias="isSuccess")
    error_codes: Optional[List[Optional[str]]] = Field(alias="errorCodes")
    hostname: Optional[str]


VerifyCaptchaToken.model_rebuild()
